ddr_oxid_devel_wiki:
    resource: "@DdrOxidDevelWikiBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

github_login:
    pattern: /login/check-github

logout:
    path:   /logout

wiki:
    resource: "@DdrGitkiBundle/Resources/config/routing.yml"
    prefix: /